# frozen_string_literal: true

source 'https://rubygems.org'

gem 'mdl'
# 0.58.0 and 0.60.0 don't seem super compatible with signatures, and
# magit doesn't seem to want to use the bundled version at the moment,
# so let's favor the more recent version and lock this via semver...
gem 'overcommit', ['>=0.60.0', '<0.61.0']
gem 'punchlist'
gem 'rake'
gem 'rspec'
gem 'rubocop', ['~> 1.52']
gem 'rubocop-rake'
# ensure version with RSpec/VerifiedDoubleReference
gem 'rubocop-rspec', ['>=2.10.0']
# ensure version with branch coverage
gem 'simplecov', ['>=0.18.0']
gem 'simplecov-lcov'
gem 'solargraph', ['>=0.50.0']
gem 'undercover'
gem 'webmock'
gem 'yard'
